### PR TITLE
ensure php7.4 compatibility

### PR DESCRIPTION
**Pull request by falkenhawk**

### CODE REVIEW

**Review by partikus — APPROVED** [review]
@falkenhawk looks good but I'm wondering if we're able to run integration tests for both MySQL versions. I cannot find these configurations at `.travis.yml`

**Comment by partikus** [comment]
> @falkenhawk looks good but I'm wondering if we're able to run integration tests for both MySQL versions. I cannot find these configurations at `.travis.yml`

Oh, I see there are `Unit tests` running at travis.org

**Comment by falkenhawk** [comment]
@partikus there are unfortunately no integration tests for mysql, https://github.com/ovos/doctrine1/pull/5#issuecomment-554681594

**Comment by partikus** [comment]
> @partikus there are unfortunately no integration tests for mysql, [#5 (comment)](https://github.com/ovos/doctrine1/pull/5#issuecomment-554681594)

Thanks! I've overlooked that.

**Pull request merged**
